/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/scene.ts"/>
/// <reference path="../objects/asset.ts"/>
/// <reference path="../objects/button.ts"/>
/// <reference path="../objects/label.ts"/>
/// <reference path="../objects/scene.ts"/>
/// <reference path="../objects/vector2.ts"/>
/// <reference path="../objects/gameobject.ts"/>
/// <reference path="../objects/ocean.ts"/>
/// <reference path="../objects/island.ts"/>
/// <reference path="../objects/player.ts"/>
/// <reference path="../objects/cloud.ts"/>
/// <reference path="../managers/collision.ts"/>
/// <reference path="../scenes/over.ts"/>
/// <reference path="../scenes/play.ts"/>
/// <reference path="../scenes/menu.ts"/> 
//# sourceMappingURL=_reference.js.map